### ISSUE TITLE
Download fails when episode title contains ':'

### ISSUE THREAD

**Issue by viv-4** [qk4/nodeupdl#1]
Reproduce with `$ nodeupdl 107`

These characters need escaping/replacing before saving.

**Comment by claydiffrient** [comment]
I'll take a look at this one.  Should have a PR up soon.

**Comment by claydiffrient** [comment]
Nevermind then... :)

**Comment by viv-4** [comment]
Issue was fixed by #3 

Feel free to send your PR though @claydiffrient if you're hacktobering
